version: '3.3'

services:
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - my_network
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - my_network
    restart: unless-stopped

  eureka-server:
    image: eureka-server:latest
    ports:
      - 8761:8761
    environment:
      - SPRING_PROFILES_ACTIVE=stage
    networks:
      - my_network

  product-service:
    image: product-service:latest
    ports:
      - 9788:9788
    environment:
      - SPRING_PROFILES_ACTIVE=stage
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - SERVER_PORT=9788
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5433/stock_management
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1
    depends_on:
      - eureka-server
      - postgres
    networks:
      - my_network

  api-gateway:
    image: api-gateway:latest
    ports:
      - 8762:8762
    environment:
      - SPRING_PROFILES_ACTIVE=stage
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - SERVER_PORT=8762
    depends_on:
      - eureka-server
      - product-service
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  postgres:
  pgadmin:
