spring:
  application:
    name: config-server
  profiles:
    active: stage

---
spring:
  config:
    activate:
      on-profile: localhost
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ArzuElibol/stockmanagement-configs.git

logging:
  level:
    root: debug
server:
  port: 8888

---

spring:
  config:
    activate:
      on-profile: stage
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ArzuElibol/stockmanagement-configs.git

logging:
  level:
    root: debug
server:
  port: 8888